apiVersion: v1
data:
  password: ZXhhbXBsZQ== #example
  username: cm9vdA== #root
  link: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nby1ub2RlcG9ydC1zdmM6MjcwMTcv # mongodb://root:example@mongo-nodeport-svc:27017/
kind: Secret
metadata:
  creationTimestamp: null
  name: mongo-creds
