---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapi
spec:
  selector:
    matchLabels:
      app: nodeapi
  replicas: 2
  template:
    metadata:
      labels:
        app: nodeapi
    spec:
      containers:
        - name: nodeapi
          image: german29/gn-nodeapi:1.1.8
#          resources:
#            limits:
#              cpu: "0.5"
#              memory: "256Mi"
#            requests:
#              cpu: "0.25"
#              memory: "128Mi"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: nodeapi
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30007